### ISSUE TITLE
Tracking: v3

### ISSUE THREAD

**Issue by U-C-S** [U-C-S/v3#2]
## Phases
- [x] Explore Static Site Generators Frameworks
- [ ] Explore Design Ideas
  - [ ] Port previous version to use new framework
  - [ ] Improve port with newer ideas
- [ ] DO IT

## Features
- [ ] `DynamicStatus` feature from v2

**Comment by vignesh-seven** [comment]
tell me when it's time to pick colors

**Comment by U-C-S** [comment]
ok i got a design idea now.... I'll do a prototype site soon, u decide the colors next

**Comment by vignesh-seven** [comment]
yay

**Comment by U-C-S** [comment]
Anytime soon™
